micronaut:
  application:
    name: mnR2dbcWithJdbcTestsIssue
datasources:
  default-jdbc:
    driverClassName: org.postgresql.Driver
netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default-r2dbc:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5432/postgres
      username: postgres
      password: ''
