micronaut:
  application:
    name: mnR2dbcWithJdbcTestsIssue
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5432/postgres
      username: postgres
      password: ''
